import { Box, Button, FormControl, TextField, Typography } from '@mui/material'
import { grey } from '@mui/material/colors'
import { Stack } from '@mui/system'
import axios from 'axios'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Chart from '../chart/Chart'
import styles from '../styles/Home.module.css'

const url = "http://172.17.76.7:8000//"
const ecgFile = "ecg001.csv"
const dataFile = "user001.json"

export default function Home() {
  const [values, setValues] = useState<Number[]>([])

  const [snore, setSnore] = useState(0);
  const [apnea, setApnea] = useState(0);
  const [presence, setPresence] = useState(0);
  const [deepSleepStart, setDeepSleepStart] = useState(0);
  const [deepSleepEnd, setDeepSleepEnd] = useState(0);

  useEffect(() => {
    const interval = setInterval(() => {
      axios
        .get(url + ecgFile)
        .then((res) => {
          const arr = values.concat(res.data);
          setValues(arr)
        })
        .catch((err) => console.error(err))
    }, 2000)

    return () => clearInterval(interval)

  }, [])

  const handleFetch = () => {
    axios
      .get(url + dataFile)
      .then((res) => {
        let result = JSON.parse(res.data)
        setApnea(result.apnea.events);
        setDeepSleepEnd(result['Deep-sleep'].end);
        setDeepSleepStart(result['Deep-sleep'].start);
        setPresence(result.apnea.presence);
        setSnore(result.snore);

      })
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Smart Pillow System</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <div className={styles.title}>
          Smart Pillow System
        </div>

        <div className={styles.grid}>
          <Box
            component="form"
            sx={{
              borderRadius: '10px',
              border: '1px solid',
              borderColor: grey[300],
              padding: '10px',
              margin: '50px',
              backgroundColor: grey[50],
            }}
            noValidate
            autoComplete="off"
          >
            <Stack direction="column" spacing={3} alignItems="center" justifyContent="center">
              <Typography variant="h5" component="div" style={{ fontWeight: '300' }}>Data Fetched</Typography>
              <FormControl>
                <Typography variant="subtitle2" sx={{ fontWeight: '800' }}>Sleep Apnea Events</Typography>
                <TextField
                  variant="outlined"
                  value={apnea}
                  InputProps={{
                    readOnly: true,
                  }} />
              </FormControl>
              <FormControl>
                <Typography variant="subtitle2" sx={{ fontWeight: '800' }}>Is Sleep Apnea Present?</Typography>
                <TextField
                  variant="outlined"
                  value={presence === 0 ? 'False' : 'True'}
                  InputProps={{
                    readOnly: true,
                  }} />
              </FormControl>
              <FormControl>
                <Typography variant="subtitle2" sx={{ fontWeight: '800' }}>Deep Sleep Start</Typography>
                <TextField
                  variant="outlined"
                  value={deepSleepStart}
                  InputProps={{
                    readOnly: true,
                  }} />
              </FormControl>
              <FormControl>
                <Typography variant="subtitle2" sx={{ fontWeight: '800' }}>Deep Sleep End</Typography>
                <TextField
                  variant="outlined"
                  value={deepSleepEnd}
                  InputProps={{
                    readOnly: true,
                  }} />
              </FormControl>
              <FormControl>
                <Typography variant="subtitle2" sx={{ fontWeight: '800' }}>Snore</Typography>
                <TextField
                  variant="outlined"
                  value={snore === 1 ? 'Present' : 'Absent'}
                  InputProps={{
                    readOnly: true,
                  }} />
              </FormControl>

              <FormControl>
                <Button variant='outlined' sx={{ width: '100%' }} onClick={handleFetch}>Fetch Data</Button>
              </FormControl>
            </Stack>
          </Box>
          <div>
            <Chart values={values} />
          </div>
        </div>
      </main>
    </div>
  )
}